### ISSUE TITLE
Error in optimize.Cameras.fit() 

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#14]
"ValueError: zero-size array to reduction operation maximum which has no identity"
Getting this error when trying to calculate the camera parameters with 4 image to world correspondence points.

**Comment by ezwelty** [comment]
@frigusgulo Thanks for reporting an issue. However, I'll need a lot more information to be able to assess the problem (and whether it is even a problem with glimpse). Please provide a minimal working example and links to the input data. If you prefer privacy, you can email me the link to the data.
