### ISSUE TITLE
Camera dict not saving certain parameters

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#20]
`params= dict(
  sensorsz=(35.9, 24),
  xyz=(393506.713, 6695855.64, 961.3370),
  viewdir=(6.55401513e+01, -1.95787507e+01,  7.90589866e+00),
  p=(1.42603100e-01,4.12163305e-01),
  k=(-4.78577912e-01,  1.08772049e+00, -1.27452460e+00,6.78479918e-01,  2.39852156e-02, -1.229e-01),
  imgsz=(7360, 4912),
  fmm=28
)

camera = glimpse.Camera(**params)

camera.as_dict()

{'xyz': [393506.713, 6695855.64, 961.337],
 'viewdir': [65.5401513, -19.5787507, 7.90589866],
 'imgsz': [7360.0, 4912.0],
 'f': [5740.389972144847, 5730.666666666667],
 'c': [0.0, 0.0],
 'k': [-0.478577912,
  1.08772049,
  -1.2745246,
  0.678479918,
  0.0239852156,
  -0.1229],
 'p': [0.1426031, 0.412163305]}`

**Comment by ezwelty** [comment]
@frigusgulo Please read the documentation before posting an issue.

`Camera.as_dict()`:
```json
"""
Return this camera as a dictionary.

Arguments:
    attributes (iterable of :obj:`str`): Attributes to include.
        If `None`, defaults to the core attributes
        (:attr:`xyz`, :attr:`viewdir`, :attr:`imgsz`, :attr:`f`, :attr:`c`, :attr:`k`, :attr:`p`).

Returns:
    dict: Attribute names and values
"""
```

So if want to keep a record of `fmm`, you could do (for example):

```python
params= dict(
  sensorsz=(35.9, 24),
  xyz=(393506.713, 6695855.64, 961.3370),
  viewdir=(6.55401513e+01, -1.95787507e+01, 7.90589866e+00),
  p=(1.42603100e-01,4.12163305e-01),
  k=(-4.78577912e-01, 1.08772049e+00, -1.27452460e+00,6.78479918e-01, 2.39852156e-02, -1.229e-01),
  imgsz=(7360, 4912),
  fmm=28
)
camera = glimpse.Camera(**params)
camera.as_dict(params.keys())
```
