### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cams'

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#22]
I am getting an inexplicable error in my code: 
https://github.com/frigusgulo/wolverineglacier/blob/master/scripts/opt_viewdirs.py#L128
Despite checking the documents, it would appear that the list of cameras is not jiving with the class instantiation. 
'''
AttributeError     Traceback (most recent call last)
~/Research/wolverine/wolverineglacier/scripts/opt_viewdirs.py in <module>
    125 
    126 
--> 127         Cameras = glimpse.optimize.Cameras([image.cam for image  in tounge_images],[tounge_matcher.matches],cam_params=dict(viewdir=True) )
    128         new_params = Cameras.fit()
    129         Cameras.set_cameras(new_params)

~/anaconda3/lib/python3.7/site-packages/glimpse/optimize.py in __init__(self, cams, controls, cam_params, group_indices, group_params, weights, scales, sparsity)
    856         # Core attributes
    857         self.cams = cams
--> 858         controls = self.__class__.prune_controls(controls, cams=self.cams)
    859         self.controls = controls
    860         ncams = len(self.cams)

~/anaconda3/lib/python3.7/site-packages/glimpse/optimize.py in prune_controls(controls, cams)
    939             list: Control which reference the cameras in `cams`
    940         """
--> 941         return [control for control in controls
    942             if len(set(cams) & set(control.cams)) > 0]
    943 

~/anaconda3/lib/python3.7/site-packages/glimpse/optimize.py in <listcomp>(.0)
    940         """
    941         return [control for control in controls
--> 942             if len(set(cams) & set(control.cams)) > 0]
    943 
    944     @staticmethod

AttributeError: 'NoneType' object has no attribute 'cams'

``

**Comment by ezwelty** [comment]
I don't have the data to run your code, but a quick glance over suggests that the problem is that `tounge_matcher.matches` is `optimize.KeypointMatcher.matches`, which is a `scipy.sparse.coo.coo_matrix`. However, `optimize.Cameras` expects a `list` of controls, with no empty values. Doing something like `list(tounge_matcher.matches.data)` should do the trick.
