### ISSUE TITLE
cam_bounds: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#23]
Code:
https://github.com/frigusgulo/wolverineglacier/blob/master/scripts/opt_viewdirs.py#L136

It looks as though self.group_indices is causing trouble. Is there any workaround? 
Using the "group_indices" argument did not help.

**
IndexError                                Traceback (most recent call last)
<ipython-input-55-b073bd3f9bd0> in <module>
----> 1 glimpse.optimize.Cameras(cams = cams, controls=np.array(tounge_matcher.matches.data),cam_params=dict(viewdir=True),group_indices=len(cams),group_params=dict(viewdir=True) )

~/anaconda3/lib/python3.7/site-packages/glimpse/optimize.py in __init__(self, cams, controls, cam_params, group_indices, group_params, weights, scales, sparsity)
    871         # Build lmfit parameters
    872         # params, cam_masks, group_masks, cam_breaks, group_breaks for set_cameras()
--> 873         self.update_params()
    874         # Test for errors
    875         self._test()

~/anaconda3/lib/python3.7/site-packages/glimpse/optimize.py in update_params(self)
   1189         for group, idx in enumerate(self.group_indices):
   1190             bounds = np.column_stack((
-> 1191                 np.column_stack([cam_bounds[i][:, 0] for i in idx]).max(axis=1),
   1192                 np.column_stack([cam_bounds[i][:, 1] for i in idx]).min(axis=1)))
   1193             mask, bounds = self.__class__.parse_params(self.group_params[group], default_bounds=bounds)

~/anaconda3/lib/python3.7/site-packages/glimpse/optimize.py in <listcomp>(.0)
   1189         for group, idx in enumerate(self.group_indices):
   1190             bounds = np.column_stack((
-> 1191                 np.column_stack([cam_bounds[i][:, 0] for i in idx]).max(axis=1),
   1192                 np.column_stack([cam_bounds[i][:, 1] for i in idx]).min(axis=1)))
   1193             mask, bounds = self.__class__.parse_params(self.group_params[group], default_bounds=bounds)

IndexError: tuple index out of range

**

**Comment by ezwelty** [comment]
You wrote:

```python
Cameras = glimpse.optimize.Cameras(
  cams = cams,
  controls=np.array(tounge_matcher.matches.data),
  cam_params=dict(viewdir=True),
  group_indices=len(cams),
  group_params=dict(viewdir=True)
)
```

where `cam_params` is `dict`, group_indices is `int`, and `group_params` is `dict`. But if you look at the documentation for `glimpse.optimize.Cameras`, you'll see it expects something entirely different:

- cam_params (list): Parameters to optimize separately for each camera (see `parse_params()`)
- group_indices (list): Integer index of `cams` belonging to each group
- group_params (list): Parameters to optimize together for all cameras in each group (see `parse_params()`)
