### ISSUE TITLE
"AttributeError: 'Lines' object has no attribute 'xyz'"

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#25]
`line 1340, in camera_scales
    xyz.append(control.xyz)
AttributeError: 'Lines' object has no attribute 'xyz'
`

https://github.com/ezwelty/glimpse/blob/rewrite/glimpse/optimize.py#L1340

I think this should be:

`xyz.append(control.xyzs)`

**Comment by ezwelty** [comment]
Oops, that's because `Lines` is currently a subclass of `Points`, so `isinstance(control, Points)` is true also if `control` is `Lines`. Fixed by b328d5ba2bf014916dbc3fea8d2274af0643cb0b.
