### ISSUE TITLE
Issue with equality types (isinstance more-so for inheritance?)

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#26]
There is a quirk here: https://github.com/ezwelty/glimpse/blob/rewrite/glimpse/optimize.py#L1340

I resolved it with this:
`
                    if type(control) is Points:
                        xyz.append(control.xyz)
                    elif type(control) is Lines:
                        xyz.extend(control.xyzs)
'

**Comment by ezwelty** [comment]
Copy-paste error in my last commit. Should now be fixed in 97361a1ecb9ad9e7f19d51c6b5e8ee5c2cdc34ad.
