### ISSUE TITLE
Sphinx error: master file glimpse/docs/contents.rst not found

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#31]
Fixed issue according to this thread: https://stackoverflow.com/questions/56336234/build-fail-sphinx-error-contents-rst-not-found

added `master_doc = "index"`  here: https://github.com/ezwelty/glimpse/blob/master/docs/conf.py#L53

**Comment by ezwelty** [comment]
The docs are built by running this from the root directory:

```bash
make docs
# Equivalent to:
# poetry run sphinx-build docs docs/build
```

Added a note in the `README.md` (#32).
